title: Faruk T. Yalcin
description: Social Psychology PhD Student @ Penn State
url: "https://faruktayyipyalcin.github.io"
baseurl: ""                        
theme: minima                  
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed


# Top nav 
header_pages:
  - publications/index.md
  - projects.md
  - cv.md

# Nice URLs
permalink: /:categories/:title/

# Collections for growth 
collections:
  publications:
    output: true
    permalink: /publications/:name/
  talks:
    output: true
    permalink: /talks/:name/

# Exclusions 
exclude:
  - README.md
  - node_modules
  - vendor
  - scripts
